// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cenjxcsfibfqzxllpixw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbmp4Y3NmaWJmcXp4bGxwaXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MzIzMDAsImV4cCI6MjA3NTMwODMwMH0.9Q-T2xshLBW6-HAQLKprYP9cxYL06or1MjX-kyP5x30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});